### PR TITLE
[FIXED JENKINS-29626] - Restore the removed constructor, add Javadoc

### PR DESCRIPTION
**Pull request by oleg-nenashev**
https://issues.jenkins-ci.org/browse/JENKINS-29626

- [x] Fix the regression caused by #16
- [x] Add some Javadocs

@reviewbybees @mrooney @carstenlenz

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Sorry, wrong remote :(

**Comment by svanoort** [comment]
:bee:

**Comment by mrooney** [comment]
Thank you! I'll release this as 1.5.

**Comment by mrooney** [comment]
Okay, this has been officially released and the Wiki is updated. This, Findbugs, and the configuration clean up made it into 1.5. Thanks for your time and help to improve this plugin!

**Pull request merged**
