### PR TITLE
[JENKINS-40447] Use AbstractSynchronousNonBlockingStepExecution

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-40447](https://issues.jenkins-ci.org/browse/JENKINS-40447)

Requires updating to 1.609.x.

@reviewbybees

### CODE REVIEW

**Comment by mrooney** [comment]
Thanks for the general clean up as well, looks great!

**Comment by jglick** [comment]
@reviewbybees done

**Comment by mrooney** [comment]
Let me know if you want me to bump the version and release or if you prefer to handle that!

**Comment by jglick** [comment]
@mrooney I suppose you are the maintainer, so please go ahead and release if you approve.

**Comment by mrooney** [comment]
I suppose I am :) Released as 1.12, thanks for the improvement!

**Pull request merged**
