### PR TITLE
Misc "backend" changes

### PR DESCRIPTION
**Pull request by rbywater**
Just a tidy up of the pom.xml file, along with creation of a Jenkinsfile so that the project will get picked up by the new Jenkins CI.

Also addition of an explicit LICENSE file just to make things clearer as to what licensing model is used.

### CODE REVIEW

**Comment by rbywater** [comment]
@mrooney , this isn't meant as a reminder as such but just realised I'm not sure how adding you as a reviewer would appear for you so not sure if you have seen this PR or not. So figured I'd just comment with a mention just in case - apologies if you've already seen the PR review request but just not had time :smile:

**Comment by rbywater** [comment]
@mrooney, I'm keen to get @fengxx's released so that people can start using the new feature so I'll merge this change as well prior to release just to pick up the latest Jenkinsfile and parent POM support. However if you have any comments please do let me know and I'll flick through any changes as another PR.

**Comment by mrooney** [comment]
Looks good! The developers seems to be a list so you could just add yourself first, but I'm not sure what the implications of being in this list are, so seems fine :)

**Comment by rbywater** [comment]
Didn't realise that it was a list so, as I want to ensure you aren't forgotten, I've added you back to the list and we can see what happens with the plugin listing etc. and fix up if/when necessary :)

**Pull request merged**
