### PR TITLE
Cleanup code and improve logging

### PR DESCRIPTION
**Pull request by pmouawad**
This PR provides the following improvements:

- Use isEmpty instead of String comparison with ""
- Replace implementation ArrayList by interface List
- Improve logging by removing e.printStackTrace() and replacing by logging messages where needed
- Make try with resources safer
- Simplify readFile
- Drop commented code
- Remove unthrown exceptions

Regards
Philippe M.

### CODE REVIEW

**Comment by pmouawad** [comment]
Hello,
Any update on this PR ?
Will it be merged ?
Thanks

**Comment by rbywater** [comment]
Looks reasonable - I'm just taking a look through it but its taking me a little while due to other commitments. Are you able to try and push a blank commit or something to force the PR checks to run again as, although I don't think it's your change that is causing the error, the last check failed. Thanks :)

**Comment by rbywater** [comment]
Thanks for the contribution!

**Comment by pmouawad** [comment]
Thanks for merging. Any release planned with it ? 
Thanks

**Comment by rbywater** [comment]
Hi @pmouawad - given there were no major visible feature changes I wasn't planning on doing a release however is there one of your changes to logging that you were hoping to use in your installation?

**Pull request merged**
