### PR TITLE
Use newer parent and jenkins-test-harness

### PR DESCRIPTION
**Pull request by jglick**
For PCT compatibility with https://github.com/jenkinsci/jenkins/pull/4944.

### CODE REVIEW

**Comment by rbywater** [comment]
Thanks @jglick - I haven't looked at the incremental stuff much but I'm assuming with this change there's no change to the normal release process etc.? If so I'm all good to merge it if you are finished.

**Comment by jglick** [comment]
You can still use `release:prepare release:perform` as usual.

**Comment by jglick** [comment]
Do you plan to release this?

**Comment by rbywater** [comment]
Sorry yes - have been trying to find some time to look at the table to div layout issue prior to releasing which I've now managed. Once that PR is merged then this will get released out.

**Pull request merged**
