### PR TITLE
Allow user to set file includes pattern

### PR DESCRIPTION
**Pull request by fengxx**
We want to archive a html file builds/blah.html, but found out all the contents of builds folder were also copied from slave to master, I think add an include pattern will fix the issue.
The change is backward compatible

### CODE REVIEW

**Comment by mrooney** [comment]
Thanks for the contribution! This has been tried twice before and caused serious bugs both times (see, https://issues.jenkins-ci.org/browse/JENKINS-16083, and https://issues.jenkins-ci.org/browse/JENKINS-7139). I am happy to review this further if you can peek at those and see if your approach at this would not cause such regressions, and also include a test case for both with and without file set patterns :) Thanks!

**Comment by aistoica** [comment]
What is the status with this pull request? I also wanted to make an implementation for this.

**Comment by mrooney** [comment]
Please see the comment above :) It needs someone to implement this, including test cases that show it doesn't break everything like the last two implementations.

**Comment by aistoica** [comment]
I tried to reproduce the issues stated in those reports and couldn't find any scenario.
`    @Test
    public void publishMultipleReportsOnBuildLevel() throws Exception {

        // Prepare the environment
        writeTestHTML("index-1.html");
        writeTestHTML("index-2.html");

        // Run the project
        final HtmlPublisherTarget target = new HtmlPublisherTarget
                ("Test Report", TEST_REPORT_DIR, "index-1.html,index-2.html", true, false, true);
        setupAndRunProject(target);

        // Ensure that the report has been attached properly
        r.assertBuildStatus(Result.SUCCESS, run);
        HtmlPublisherTarget.HTMLAction jobReport = job.getAction(HtmlPublisherTarget.HTMLAction.class);
        assertEquals(3, jobReport.getHTMLTarget().getArchiveTarget(run).list().size());
        assertEquals(1, jobReport.getHTMLTarget().getArchiveTarget(run).list("htmlpublisher-wrapper.html").length);
        assertEquals(1, jobReport.getHTMLTarget().getArchiveTarget(run).list("index-1.html").length);
        assertEquals(1, jobReport.getHTMLTarget().getArchiveTarget(run).list("index-2.html").length);
    }`

After this I checked the htmlpublisher-wrapper.html file and everything seems ok. I worked on the 1.7 code. Any suggestions?

**Comment by fengxx** [comment]
I don't think it will cause regression issues, it is totally different feature.

the issue you mentioned introduce multiple Report dir , based on the commit 
https://github.com/jenkinsci/htmlpublisher-plugin/commit/7dbff2b015d5eead296e73d697dd31e720039224

this change is just use fine-grained includes files ( change **/* to configurable )

Testcase added

**Comment by mrooney** [comment]
You are right, I understand the difference now after looking more in depth. I checked this out and ran it and I couldn't find the field to configure this pattern in the settings. Should it appear when configuring the job, or is it a configuration at the system level? Just let me know how to QA this and I'll do so and merge and release :) Thanks again for the cool feature!

**Comment by fengxx** [comment]
Thanks for review, the options is put in the "Publishing options" section

**Comment by fengxx** [comment]
rebased the commit

**Comment by rbywater** [comment]
Thanks for the updated PR. I've just reviewed the changes and there appears to a slight bug present if you clear out the Includes field. In this case, which is probably a very common use case when the user decdies they don't want to filter the output anymore, nothing gets published and you just end up with an error screen when you try and view the HTML report.

Are you able to fix the behaviour so that the "user removes Include options" use-case is covered? 

Apart from that it's looking good so once that is fixed up it should be all good to go. Apologies for missing that in my first run through!

**Comment by rbywater** [comment]
Great work - looks like it works wonderfully. Apologies for the length of time taken to review this - GitHub didn't actually let me know that you'd posted a new commit to the PR and so it was only by chance that I was passing through that I found your fix. 

Will merge now and then will do a release once my other tidy up PR is also merged.

Thanks again for your contribution.

**Comment by mrooney** [comment]
Thanks so much @fengxx and @rbywater 👍

**Comment by madhupmanihp** [comment]
@fengxx  Hi,Once I provided the same pattern as you provided,build failure is happening ....

**Comment by rbywater** [comment]
Can you please raise this as an issue via the issues.jenkins-ci.org issue
tracker rather than doing it via an old pull request as it's then easier to
track.

Please include as much detail as possible including the version number of
the plugin and the exact configuration you currently have set.

Thanks!

**Pull request merged**
